import { Repository } from "@/shared/interface/repository.interface";

export const dummyRepository: Repository[] = [
	{
			"id": 450892264,
			"name": "authNodeJS-App",
			"full_name": "pPlanello/authNodeJS-App",
			"private": false,
			"owner": {
					"login": "pPlanello",
					"id": 36472624,
					"node_id": "MDQ6VXNlcjM2NDcyNjI0",
					"avatar_url": "https://avatars.githubusercontent.com/u/36472624?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/pPlanello",
					"html_url": "https://github.com/pPlanello",
					"followers_url": "https://api.github.com/users/pPlanello/followers",
					"following_url": "https://api.github.com/users/pPlanello/following{/other_user}",
					"gists_url": "https://api.github.com/users/pPlanello/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/pPlanello/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/pPlanello/subscriptions",
					"organizations_url": "https://api.github.com/users/pPlanello/orgs",
					"repos_url": "https://api.github.com/users/pPlanello/repos",
					"events_url": "https://api.github.com/users/pPlanello/events{/privacy}",
					"received_events_url": "https://api.github.com/users/pPlanello/received_events",
					"type": "User",
					"site_admin": false
			},
			"html_url": "https://github.com/pPlanello/authNodeJS-App",
			"description": null,
			"url": "https://api.github.com/repos/pPlanello/authNodeJS-App",
			"created_at": new Date("2022-01-22T17:48:14Z"),
			"updated_at":new Date("2022-01-24T10:00:32Z"),
			"pushed_at": new Date("2022-01-24T12:24:55Z"),
			"git_url": "git://github.com/pPlanello/authNodeJS-App.git",
			"ssh_url": "git@github.com:pPlanello/authNodeJS-App.git",
			"clone_url": "https://github.com/pPlanello/authNodeJS-App.git",
			"svn_url": "https://github.com/pPlanello/authNodeJS-App",
			"homepage": "",
			"size": 17,
			"stargazers_count": 0,
			"watchers_count": 0,
			"language": "JavaScript",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"has_discussions": false,
			"forks_count": 0,
			"mirror_url": null,
			"archived": false,
			"disabled": false,
			"open_issues_count": 0,
			"license": null,
			"allow_forking": true,
			"is_template": false,
			"web_commit_signoff_required": false,
			"topics": [
					"express",
					"jwt",
					"nodejs"
			],
			"visibility": "public",
			"forks": 0,
			"open_issues": 0,
			"watchers": 0,
			"default_branch": "master",
			"permissions": {
					"admin": true,
					"maintain": true,
					"push": true,
					"triage": true,
					"pull": true
			}
	},
	{
			"id": 451489769,
			"name": "classWeb3",
			"full_name": "pPlanello/classWeb3",
			"private": false,
			"owner": {
					"login": "pPlanello",
					"id": 36472624,
					"node_id": "MDQ6VXNlcjM2NDcyNjI0",
					"avatar_url": "https://avatars.githubusercontent.com/u/36472624?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/pPlanello",
					"html_url": "https://github.com/pPlanello",
					"followers_url": "https://api.github.com/users/pPlanello/followers",
					"following_url": "https://api.github.com/users/pPlanello/following{/other_user}",
					"gists_url": "https://api.github.com/users/pPlanello/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/pPlanello/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/pPlanello/subscriptions",
					"organizations_url": "https://api.github.com/users/pPlanello/orgs",
					"repos_url": "https://api.github.com/users/pPlanello/repos",
					"events_url": "https://api.github.com/users/pPlanello/events{/privacy}",
					"received_events_url": "https://api.github.com/users/pPlanello/received_events",
					"type": "User",
					"site_admin": false
			},
			"html_url": "https://github.com/pPlanello/classWeb3",
			"description": null,
			"url": "https://api.github.com/repos/pPlanello/classWeb3",
			"created_at": new Date("2022-01-24T14:08:51Z"),
			"updated_at": new Date("2022-10-26T20:04:33Z"),
			"pushed_at": new Date("2022-01-24T14:17:07Z"),
			"git_url": "git://github.com/pPlanello/classWeb3.git",
			"ssh_url": "git@github.com:pPlanello/classWeb3.git",
			"clone_url": "https://github.com/pPlanello/classWeb3.git",
			"svn_url": "https://github.com/pPlanello/classWeb3",
			"homepage": "class-web3.vercel.app",
			"size": 467,
			"stargazers_count": 0,
			"watchers_count": 0,
			"language": "JavaScript",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"has_discussions": false,
			"forks_count": 0,
			"mirror_url": null,
			"archived": false,
			"disabled": false,
			"open_issues_count": 0,
			"license": null,
			"allow_forking": true,
			"is_template": false,
			"web_commit_signoff_required": false,
			"topics": [
					"reactjs",
					"solidity",
					"web3"
			],
			"visibility": "public",
			"forks": 0,
			"open_issues": 0,
			"watchers": 0,
			"default_branch": "master",
			"permissions": {
					"admin": true,
					"maintain": true,
					"push": true,
					"triage": true,
					"pull": true
			}
	},
	{
			"id": 553720822,
			"name": "Cloud-Home--Backend",
			"full_name": "pPlanello/Cloud-Home--Backend",
			"private": false,
			"owner": {
					"login": "pPlanello",
					"id": 36472624,
					"node_id": "MDQ6VXNlcjM2NDcyNjI0",
					"avatar_url": "https://avatars.githubusercontent.com/u/36472624?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/pPlanello",
					"html_url": "https://github.com/pPlanello",
					"followers_url": "https://api.github.com/users/pPlanello/followers",
					"following_url": "https://api.github.com/users/pPlanello/following{/other_user}",
					"gists_url": "https://api.github.com/users/pPlanello/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/pPlanello/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/pPlanello/subscriptions",
					"organizations_url": "https://api.github.com/users/pPlanello/orgs",
					"repos_url": "https://api.github.com/users/pPlanello/repos",
					"events_url": "https://api.github.com/users/pPlanello/events{/privacy}",
					"received_events_url": "https://api.github.com/users/pPlanello/received_events",
					"type": "User",
					"site_admin": false
			},
			"html_url": "https://github.com/pPlanello/Cloud-Home--Backend",
			"description": null,
			"url": "https://api.github.com/repos/pPlanello/Cloud-Home--Backend",
			"created_at": new Date("2022-10-18T16:56:21Z"),
			"updated_at": new Date("2022-10-18T17:19:07Z"),
			"pushed_at": new Date("2022-10-25T18:00:55Z"),
			"git_url": "git://github.com/pPlanello/Cloud-Home--Backend.git",
			"ssh_url": "git@github.com:pPlanello/Cloud-Home--Backend.git",
			"clone_url": "https://github.com/pPlanello/Cloud-Home--Backend.git",
			"svn_url": "https://github.com/pPlanello/Cloud-Home--Backend",
			"homepage": "",
			"size": 16,
			"stargazers_count": 1,
			"watchers_count": 1,
			"language": "TypeScript",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"has_discussions": false,
			"forks_count": 0,
			"mirror_url": null,
			"archived": false,
			"disabled": false,
			"open_issues_count": 0,
			"license": null,
			"allow_forking": true,
			"is_template": false,
			"web_commit_signoff_required": false,
			"topics": [
					"express",
					"mongodb",
					"nodejs",
					"typescript"
			],
			"visibility": "public",
			"forks": 0,
			"open_issues": 0,
			"watchers": 1,
			"default_branch": "master",
			"permissions": {
					"admin": true,
					"maintain": true,
					"push": true,
					"triage": true,
					"pull": true
			}
	},
	{
			"id": 424636674,
			"name": "countriesApp",
			"full_name": "pPlanello/countriesApp",
			"private": false,
			"owner": {
					"login": "pPlanello",
					"id": 36472624,
					"node_id": "MDQ6VXNlcjM2NDcyNjI0",
					"avatar_url": "https://avatars.githubusercontent.com/u/36472624?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/pPlanello",
					"html_url": "https://github.com/pPlanello",
					"followers_url": "https://api.github.com/users/pPlanello/followers",
					"following_url": "https://api.github.com/users/pPlanello/following{/other_user}",
					"gists_url": "https://api.github.com/users/pPlanello/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/pPlanello/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/pPlanello/subscriptions",
					"organizations_url": "https://api.github.com/users/pPlanello/orgs",
					"repos_url": "https://api.github.com/users/pPlanello/repos",
					"events_url": "https://api.github.com/users/pPlanello/events{/privacy}",
					"received_events_url": "https://api.github.com/users/pPlanello/received_events",
					"type": "User",
					"site_admin": false
			},
			"html_url": "https://github.com/pPlanello/countriesApp",
			"description": null,
			"url": "https://api.github.com/repos/pPlanello/countriesApp",
			"created_at": new Date("2021-11-04T15:02:01Z"),
			"updated_at": new Date("2023-04-26T13:54:20Z"),
			"pushed_at": new Date("2021-12-23T12:58:16Z"),
			"git_url": "git://github.com/pPlanello/countriesApp.git",
			"ssh_url": "git@github.com:pPlanello/countriesApp.git",
			"clone_url": "https://github.com/pPlanello/countriesApp.git",
			"svn_url": "https://github.com/pPlanello/countriesApp",
			"homepage": "countries-app-pplanello.vercel.app",
			"size": 297,
			"stargazers_count": 1,
			"watchers_count": 1,
			"language": "TypeScript",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"has_discussions": false,
			"forks_count": 0,
			"mirror_url": null,
			"archived": false,
			"disabled": false,
			"open_issues_count": 0,
			"license": null,
			"allow_forking": true,
			"is_template": false,
			"web_commit_signoff_required": false,
			"topics": [
					"angular"
			],
			"visibility": "public",
			"forks": 0,
			"open_issues": 0,
			"watchers": 1,
			"default_branch": "master",
			"permissions": {
					"admin": true,
					"maintain": true,
					"push": true,
					"triage": true,
					"pull": true
			}
	},
	{
			"id": 580501375,
			"name": "expensesTrackerApp",
			"full_name": "pPlanello/expensesTrackerApp",
			"private": false,
			"owner": {
					"login": "pPlanello",
					"id": 36472624,
					"node_id": "MDQ6VXNlcjM2NDcyNjI0",
					"avatar_url": "https://avatars.githubusercontent.com/u/36472624?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/pPlanello",
					"html_url": "https://github.com/pPlanello",
					"followers_url": "https://api.github.com/users/pPlanello/followers",
					"following_url": "https://api.github.com/users/pPlanello/following{/other_user}",
					"gists_url": "https://api.github.com/users/pPlanello/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/pPlanello/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/pPlanello/subscriptions",
					"organizations_url": "https://api.github.com/users/pPlanello/orgs",
					"repos_url": "https://api.github.com/users/pPlanello/repos",
					"events_url": "https://api.github.com/users/pPlanello/events{/privacy}",
					"received_events_url": "https://api.github.com/users/pPlanello/received_events",
					"type": "User",
					"site_admin": false
			},
			"html_url": "https://github.com/pPlanello/expensesTrackerApp",
			"description": "It is an application to register your expenses and have them controlled from the web. By default, dummy data is loaded to visualize some of the fields and functionalities.",
			"url": "https://api.github.com/repos/pPlanello/expensesTrackerApp",
			"created_at": new Date("2022-12-20T18:07:32Z"),
			"updated_at": new Date("2023-07-10T16:37:10Z"),
			"pushed_at": new Date("2023-07-10T10:37:56Z"),
			"git_url": "git://github.com/pPlanello/expensesTrackerApp.git",
			"ssh_url": "git@github.com:pPlanello/expensesTrackerApp.git",
			"clone_url": "https://github.com/pPlanello/expensesTrackerApp.git",
			"svn_url": "https://github.com/pPlanello/expensesTrackerApp",
			"homepage": "https://expenses-tracker-app-omega.vercel.app",
			"size": 220,
			"stargazers_count": 1,
			"watchers_count": 1,
			"language": "JavaScript",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"has_discussions": false,
			"forks_count": 0,
			"mirror_url": null,
			"archived": false,
			"disabled": false,
			"open_issues_count": 0,
			"license": null,
			"allow_forking": true,
			"is_template": false,
			"web_commit_signoff_required": false,
			"topics": [
					"reactjs"
			],
			"visibility": "public",
			"forks": 0,
			"open_issues": 0,
			"watchers": 1,
			"default_branch": "master",
			"permissions": {
					"admin": true,
					"maintain": true,
					"push": true,
					"triage": true,
					"pull": true
			}
	},
	{
			"id": 467080698,
			"name": "food-tracker-backend",
			"full_name": "pPlanello/food-tracker-backend",
			"private": false,
			"owner": {
					"login": "pPlanello",
					"id": 36472624,
					"node_id": "MDQ6VXNlcjM2NDcyNjI0",
					"avatar_url": "https://avatars.githubusercontent.com/u/36472624?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/pPlanello",
					"html_url": "https://github.com/pPlanello",
					"followers_url": "https://api.github.com/users/pPlanello/followers",
					"following_url": "https://api.github.com/users/pPlanello/following{/other_user}",
					"gists_url": "https://api.github.com/users/pPlanello/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/pPlanello/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/pPlanello/subscriptions",
					"organizations_url": "https://api.github.com/users/pPlanello/orgs",
					"repos_url": "https://api.github.com/users/pPlanello/repos",
					"events_url": "https://api.github.com/users/pPlanello/events{/privacy}",
					"received_events_url": "https://api.github.com/users/pPlanello/received_events",
					"type": "User",
					"site_admin": false
			},
			"html_url": "https://github.com/pPlanello/food-tracker-backend",
			"description": null,
			"url": "https://api.github.com/repos/pPlanello/food-tracker-backend",
			"created_at": new Date("2022-03-07T12:16:30Z"),
			"updated_at": new Date("2022-03-11T18:33:48Z"),
			"pushed_at": new Date("2022-03-08T19:34:35Z"),
			"git_url": "git://github.com/pPlanello/food-tracker-backend.git",
			"ssh_url": "git@github.com:pPlanello/food-tracker-backend.git",
			"clone_url": "https://github.com/pPlanello/food-tracker-backend.git",
			"svn_url": "https://github.com/pPlanello/food-tracker-backend",
			"homepage": "",
			"size": 135,
			"stargazers_count": 0,
			"watchers_count": 0,
			"language": "Java",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"has_discussions": false,
			"forks_count": 0,
			"mirror_url": null,
			"archived": false,
			"disabled": false,
			"open_issues_count": 0,
			"license": null,
			"allow_forking": true,
			"is_template": false,
			"web_commit_signoff_required": false,
			"topics": [
					"gradle",
					"java-17",
					"liquibase",
					"lombok",
					"postgresql",
					"swagger"
			],
			"visibility": "public",
			"forks": 0,
			"open_issues": 0,
			"watchers": 0,
			"default_branch": "master",
			"permissions": {
					"admin": true,
					"maintain": true,
					"push": true,
					"triage": true,
					"pull": true
			}
	},
	{
			"id": 584715848,
			"name": "foodOrderApp",
			"full_name": "pPlanello/foodOrderApp",
			"private": false,
			"owner": {
					"login": "pPlanello",
					"id": 36472624,
					"node_id": "MDQ6VXNlcjM2NDcyNjI0",
					"avatar_url": "https://avatars.githubusercontent.com/u/36472624?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/pPlanello",
					"html_url": "https://github.com/pPlanello",
					"followers_url": "https://api.github.com/users/pPlanello/followers",
					"following_url": "https://api.github.com/users/pPlanello/following{/other_user}",
					"gists_url": "https://api.github.com/users/pPlanello/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/pPlanello/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/pPlanello/subscriptions",
					"organizations_url": "https://api.github.com/users/pPlanello/orgs",
					"repos_url": "https://api.github.com/users/pPlanello/repos",
					"events_url": "https://api.github.com/users/pPlanello/events{/privacy}",
					"received_events_url": "https://api.github.com/users/pPlanello/received_events",
					"type": "User",
					"site_admin": false
			},
			"html_url": "https://github.com/pPlanello/foodOrderApp",
			"description": null,
			"url": "https://api.github.com/repos/pPlanello/foodOrderApp",
			"created_at": new Date("2023-01-03T10:30:03Z"),
			"updated_at": new Date("2023-04-26T13:55:55Z"),
			"pushed_at": new Date("2023-02-15T19:06:15Z"),
			"git_url": "git://github.com/pPlanello/foodOrderApp.git",
			"ssh_url": "git@github.com:pPlanello/foodOrderApp.git",
			"clone_url": "https://github.com/pPlanello/foodOrderApp.git",
			"svn_url": "https://github.com/pPlanello/foodOrderApp",
			"homepage": "https://food-order-app-swart.vercel.app/",
			"size": 3059,
			"stargazers_count": 1,
			"watchers_count": 1,
			"language": "JavaScript",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"has_discussions": false,
			"forks_count": 0,
			"mirror_url": null,
			"archived": false,
			"disabled": false,
			"open_issues_count": 0,
			"license": null,
			"allow_forking": true,
			"is_template": false,
			"web_commit_signoff_required": false,
			"topics": [
					"firebase",
					"reactjs"
			],
			"visibility": "public",
			"forks": 0,
			"open_issues": 0,
			"watchers": 1,
			"default_branch": "master",
			"permissions": {
					"admin": true,
					"maintain": true,
					"push": true,
					"triage": true,
					"pull": true
			}
	},
	{
			"id": 447170943,
			"name": "formAppAngular",
			"full_name": "pPlanello/formAppAngular",
			"private": false,
			"owner": {
					"login": "pPlanello",
					"id": 36472624,
					"node_id": "MDQ6VXNlcjM2NDcyNjI0",
					"avatar_url": "https://avatars.githubusercontent.com/u/36472624?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/pPlanello",
					"html_url": "https://github.com/pPlanello",
					"followers_url": "https://api.github.com/users/pPlanello/followers",
					"following_url": "https://api.github.com/users/pPlanello/following{/other_user}",
					"gists_url": "https://api.github.com/users/pPlanello/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/pPlanello/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/pPlanello/subscriptions",
					"organizations_url": "https://api.github.com/users/pPlanello/orgs",
					"repos_url": "https://api.github.com/users/pPlanello/repos",
					"events_url": "https://api.github.com/users/pPlanello/events{/privacy}",
					"received_events_url": "https://api.github.com/users/pPlanello/received_events",
					"type": "User",
					"site_admin": false
			},
			"html_url": "https://github.com/pPlanello/formAppAngular",
			"description": null,
			"url": "https://api.github.com/repos/pPlanello/formAppAngular",
			"created_at": new Date("2022-01-12T10:21:18Z"),
			"updated_at": new Date("2022-01-24T09:56:59Z"),
			"pushed_at": new Date("2022-01-20T17:47:09Z"),
			"git_url": "git://github.com/pPlanello/formAppAngular.git",
			"ssh_url": "git@github.com:pPlanello/formAppAngular.git",
			"clone_url": "https://github.com/pPlanello/formAppAngular.git",
			"svn_url": "https://github.com/pPlanello/formAppAngular",
			"homepage": "",
			"size": 160,
			"stargazers_count": 0,
			"watchers_count": 0,
			"language": "TypeScript",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"has_discussions": false,
			"forks_count": 0,
			"mirror_url": null,
			"archived": false,
			"disabled": false,
			"open_issues_count": 0,
			"license": null,
			"allow_forking": true,
			"is_template": false,
			"web_commit_signoff_required": false,
			"topics": [
					"angular"
			],
			"visibility": "public",
			"forks": 0,
			"open_issues": 0,
			"watchers": 0,
			"default_branch": "master",
			"permissions": {
					"admin": true,
					"maintain": true,
					"push": true,
					"triage": true,
					"pull": true
			}
	},
	{
			"id": 421764848,
			"name": "giffsApp",
			"full_name": "pPlanello/giffsApp",
			"private": false,
			"owner": {
					"login": "pPlanello",
					"id": 36472624,
					"node_id": "MDQ6VXNlcjM2NDcyNjI0",
					"avatar_url": "https://avatars.githubusercontent.com/u/36472624?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/pPlanello",
					"html_url": "https://github.com/pPlanello",
					"followers_url": "https://api.github.com/users/pPlanello/followers",
					"following_url": "https://api.github.com/users/pPlanello/following{/other_user}",
					"gists_url": "https://api.github.com/users/pPlanello/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/pPlanello/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/pPlanello/subscriptions",
					"organizations_url": "https://api.github.com/users/pPlanello/orgs",
					"repos_url": "https://api.github.com/users/pPlanello/repos",
					"events_url": "https://api.github.com/users/pPlanello/events{/privacy}",
					"received_events_url": "https://api.github.com/users/pPlanello/received_events",
					"type": "User",
					"site_admin": false
			},
			"html_url": "https://github.com/pPlanello/giffsApp",
			"description": null,
			"url": "https://api.github.com/repos/pPlanello/giffsApp",
			"created_at": new Date("2021-10-27T09:59:40Z"),
			"updated_at": new Date("2022-10-26T20:02:45Z"),
			"pushed_at": new Date("2021-11-04T14:01:56Z"),
			"git_url": "git://github.com/pPlanello/giffsApp.git",
			"ssh_url": "git@github.com:pPlanello/giffsApp.git",
			"clone_url": "https://github.com/pPlanello/giffsApp.git",
			"svn_url": "https://github.com/pPlanello/giffsApp",
			"homepage": "giffs-app-nine.vercel.app",
			"size": 382,
			"stargazers_count": 0,
			"watchers_count": 0,
			"language": "TypeScript",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"has_discussions": false,
			"forks_count": 0,
			"mirror_url": null,
			"archived": false,
			"disabled": false,
			"open_issues_count": 0,
			"license": null,
			"allow_forking": true,
			"is_template": false,
			"web_commit_signoff_required": false,
			"topics": [
					"angular"
			],
			"visibility": "public",
			"forks": 0,
			"open_issues": 0,
			"watchers": 0,
			"default_branch": "master",
			"permissions": {
					"admin": true,
					"maintain": true,
					"push": true,
					"triage": true,
					"pull": true
			}
	},
	{
			"id": 442533740,
			"name": "heroesApp",
			"full_name": "pPlanello/heroesApp",
			"private": false,
			"owner": {
					"login": "pPlanello",
					"id": 36472624,
					"node_id": "MDQ6VXNlcjM2NDcyNjI0",
					"avatar_url": "https://avatars.githubusercontent.com/u/36472624?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/pPlanello",
					"html_url": "https://github.com/pPlanello",
					"followers_url": "https://api.github.com/users/pPlanello/followers",
					"following_url": "https://api.github.com/users/pPlanello/following{/other_user}",
					"gists_url": "https://api.github.com/users/pPlanello/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/pPlanello/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/pPlanello/subscriptions",
					"organizations_url": "https://api.github.com/users/pPlanello/orgs",
					"repos_url": "https://api.github.com/users/pPlanello/repos",
					"events_url": "https://api.github.com/users/pPlanello/events{/privacy}",
					"received_events_url": "https://api.github.com/users/pPlanello/received_events",
					"type": "User",
					"site_admin": false
			},
			"html_url": "https://github.com/pPlanello/heroesApp",
			"description": null,
			"url": "https://api.github.com/repos/pPlanello/heroesApp",
			"created_at": new Date("2021-12-28T17:19:13Z"),
			"updated_at": new Date("2022-10-26T20:12:27Z"),
			"pushed_at": new Date("2022-10-26T20:59:29Z"),
			"git_url": "git://github.com/pPlanello/heroesApp.git",
			"ssh_url": "git@github.com:pPlanello/heroesApp.git",
			"clone_url": "https://github.com/pPlanello/heroesApp.git",
			"svn_url": "https://github.com/pPlanello/heroesApp",
			"homepage": "heroes-app-gules-chi.vercel.app",
			"size": 8052,
			"stargazers_count": 0,
			"watchers_count": 0,
			"language": "TypeScript",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"has_discussions": false,
			"forks_count": 0,
			"mirror_url": null,
			"archived": false,
			"disabled": false,
			"open_issues_count": 0,
			"license": null,
			"allow_forking": true,
			"is_template": false,
			"web_commit_signoff_required": false,
			"topics": [
					"angular"
			],
			"visibility": "public",
			"forks": 0,
			"open_issues": 0,
			"watchers": 0,
			"default_branch": "master",
			"permissions": {
					"admin": true,
					"maintain": true,
					"push": true,
					"triage": true,
					"pull": true
			}
	},
	{
			"id": 444036093,
			"name": "heroesApp-backend",
			"full_name": "pPlanello/heroesApp-backend",
			"private": false,
			"owner": {
					"login": "pPlanello",
					"id": 36472624,
					"node_id": "MDQ6VXNlcjM2NDcyNjI0",
					"avatar_url": "https://avatars.githubusercontent.com/u/36472624?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/pPlanello",
					"html_url": "https://github.com/pPlanello",
					"followers_url": "https://api.github.com/users/pPlanello/followers",
					"following_url": "https://api.github.com/users/pPlanello/following{/other_user}",
					"gists_url": "https://api.github.com/users/pPlanello/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/pPlanello/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/pPlanello/subscriptions",
					"organizations_url": "https://api.github.com/users/pPlanello/orgs",
					"repos_url": "https://api.github.com/users/pPlanello/repos",
					"events_url": "https://api.github.com/users/pPlanello/events{/privacy}",
					"received_events_url": "https://api.github.com/users/pPlanello/received_events",
					"type": "User",
					"site_admin": false
			},
			"html_url": "https://github.com/pPlanello/heroesApp-backend",
			"description": null,
			"url": "https://api.github.com/repos/pPlanello/heroesApp-backend",
			"created_at": new Date("2022-01-03T11:26:29Z"),
			"updated_at": new Date("2022-01-03T11:26:33Z"),
			"pushed_at": new Date("2022-01-11T10:47:36Z"),
			"git_url": "git://github.com/pPlanello/heroesApp-backend.git",
			"ssh_url": "git@github.com:pPlanello/heroesApp-backend.git",
			"clone_url": "https://github.com/pPlanello/heroesApp-backend.git",
			"svn_url": "https://github.com/pPlanello/heroesApp-backend",
			"homepage": null,
			"size": 2,
			"stargazers_count": 0,
			"watchers_count": 0,
			"language": null,
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"has_discussions": false,
			"forks_count": 0,
			"mirror_url": null,
			"archived": false,
			"disabled": false,
			"open_issues_count": 0,
			"license": null,
			"allow_forking": true,
			"is_template": false,
			"web_commit_signoff_required": false,
			"topics": [],
			"visibility": "public",
			"forks": 0,
			"open_issues": 0,
			"watchers": 0,
			"default_branch": "master",
			"permissions": {
					"admin": true,
					"maintain": true,
					"push": true,
					"triage": true,
					"pull": true
			}
	},
	{
			"id": 495507889,
			"name": "learningRestNodeJS",
			"full_name": "pPlanello/learningRestNodeJS",
			"private": false,
			"owner": {
					"login": "pPlanello",
					"id": 36472624,
					"node_id": "MDQ6VXNlcjM2NDcyNjI0",
					"avatar_url": "https://avatars.githubusercontent.com/u/36472624?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/pPlanello",
					"html_url": "https://github.com/pPlanello",
					"followers_url": "https://api.github.com/users/pPlanello/followers",
					"following_url": "https://api.github.com/users/pPlanello/following{/other_user}",
					"gists_url": "https://api.github.com/users/pPlanello/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/pPlanello/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/pPlanello/subscriptions",
					"organizations_url": "https://api.github.com/users/pPlanello/orgs",
					"repos_url": "https://api.github.com/users/pPlanello/repos",
					"events_url": "https://api.github.com/users/pPlanello/events{/privacy}",
					"received_events_url": "https://api.github.com/users/pPlanello/received_events",
					"type": "User",
					"site_admin": false
			},
			"html_url": "https://github.com/pPlanello/learningRestNodeJS",
			"description": null,
			"url": "https://api.github.com/repos/pPlanello/learningRestNodeJS",
			"created_at": new Date("2022-05-23T17:24:34Z"),
			"updated_at": new Date("2022-10-11T09:18:29Z"),
			"pushed_at": new Date("2022-09-10T17:06:27Z"),
			"git_url": "git://github.com/pPlanello/learningRestNodeJS.git",
			"ssh_url": "git@github.com:pPlanello/learningRestNodeJS.git",
			"clone_url": "https://github.com/pPlanello/learningRestNodeJS.git",
			"svn_url": "https://github.com/pPlanello/learningRestNodeJS",
			"homepage": "",
			"size": 111,
			"stargazers_count": 0,
			"watchers_count": 0,
			"language": "JavaScript",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"has_discussions": false,
			"forks_count": 0,
			"mirror_url": null,
			"archived": false,
			"disabled": false,
			"open_issues_count": 0,
			"license": null,
			"allow_forking": true,
			"is_template": false,
			"web_commit_signoff_required": false,
			"topics": [
					"mongodb",
					"mongoose",
					"nodejs"
			],
			"visibility": "public",
			"forks": 0,
			"open_issues": 0,
			"watchers": 0,
			"default_branch": "master",
			"permissions": {
					"admin": true,
					"maintain": true,
					"push": true,
					"triage": true,
					"pull": true
			}
	},
	{
			"id": 169559056,
			"name": "mini_project_C",
			"full_name": "pPlanello/mini_project_C",
			"private": false,
			"owner": {
					"login": "pPlanello",
					"id": 36472624,
					"node_id": "MDQ6VXNlcjM2NDcyNjI0",
					"avatar_url": "https://avatars.githubusercontent.com/u/36472624?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/pPlanello",
					"html_url": "https://github.com/pPlanello",
					"followers_url": "https://api.github.com/users/pPlanello/followers",
					"following_url": "https://api.github.com/users/pPlanello/following{/other_user}",
					"gists_url": "https://api.github.com/users/pPlanello/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/pPlanello/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/pPlanello/subscriptions",
					"organizations_url": "https://api.github.com/users/pPlanello/orgs",
					"repos_url": "https://api.github.com/users/pPlanello/repos",
					"events_url": "https://api.github.com/users/pPlanello/events{/privacy}",
					"received_events_url": "https://api.github.com/users/pPlanello/received_events",
					"type": "User",
					"site_admin": false
			},
			"html_url": "https://github.com/pPlanello/mini_project_C",
			"description": null,
			"url": "https://api.github.com/repos/pPlanello/mini_project_C",
			"created_at": new Date("2019-02-07T11:09:35Z"),
			"updated_at": new Date("2021-11-04T14:59:08Z"),
			"pushed_at": new Date("2021-11-04T14:59:04Z"),
			"git_url": "git://github.com/pPlanello/mini_project_C.git",
			"ssh_url": "git@github.com:pPlanello/mini_project_C.git",
			"clone_url": "https://github.com/pPlanello/mini_project_C.git",
			"svn_url": "https://github.com/pPlanello/mini_project_C",
			"homepage": null,
			"size": 9312,
			"stargazers_count": 0,
			"watchers_count": 0,
			"language": "C",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"has_discussions": false,
			"forks_count": 0,
			"mirror_url": null,
			"archived": false,
			"disabled": false,
			"open_issues_count": 0,
			"license": null,
			"allow_forking": true,
			"is_template": false,
			"web_commit_signoff_required": false,
			"topics": [],
			"visibility": "public",
			"forks": 0,
			"open_issues": 0,
			"watchers": 0,
			"default_branch": "master",
			"permissions": {
					"admin": true,
					"maintain": true,
					"push": true,
					"triage": true,
					"pull": true
			}
	},
	{
			"id": 653736776,
			"name": "portfolio",
			"full_name": "pPlanello/portfolio",
			"private": false,
			"owner": {
					"login": "pPlanello",
					"id": 36472624,
					"node_id": "MDQ6VXNlcjM2NDcyNjI0",
					"avatar_url": "https://avatars.githubusercontent.com/u/36472624?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/pPlanello",
					"html_url": "https://github.com/pPlanello",
					"followers_url": "https://api.github.com/users/pPlanello/followers",
					"following_url": "https://api.github.com/users/pPlanello/following{/other_user}",
					"gists_url": "https://api.github.com/users/pPlanello/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/pPlanello/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/pPlanello/subscriptions",
					"organizations_url": "https://api.github.com/users/pPlanello/orgs",
					"repos_url": "https://api.github.com/users/pPlanello/repos",
					"events_url": "https://api.github.com/users/pPlanello/events{/privacy}",
					"received_events_url": "https://api.github.com/users/pPlanello/received_events",
					"type": "User",
					"site_admin": false
			},
			"html_url": "https://github.com/pPlanello/portfolio",
			"description": "My personal website portfolio",
			"url": "https://api.github.com/repos/pPlanello/portfolio",
			"created_at": new Date("2023-06-14T16:12:38Z"),
			"updated_at": new Date("2023-06-20T14:56:30Z"),
			"pushed_at": new Date("2023-07-10T16:42:17Z"),
			"git_url": "git://github.com/pPlanello/portfolio.git",
			"ssh_url": "git@github.com:pPlanello/portfolio.git",
			"clone_url": "https://github.com/pPlanello/portfolio.git",
			"svn_url": "https://github.com/pPlanello/portfolio",
			"homepage": null,
			"size": 273,
			"stargazers_count": 1,
			"watchers_count": 1,
			"language": "TypeScript",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"has_discussions": false,
			"forks_count": 0,
			"mirror_url": null,
			"archived": false,
			"disabled": false,
			"open_issues_count": 0,
			"license": null,
			"allow_forking": true,
			"is_template": false,
			"web_commit_signoff_required": false,
			"topics": [],
			"visibility": "public",
			"forks": 0,
			"open_issues": 0,
			"watchers": 1,
			"default_branch": "master",
			"permissions": {
					"admin": true,
					"maintain": true,
					"push": true,
					"triage": true,
					"pull": true
			}
	},
	{
			"id": 570094686,
			"name": "pPlanello",
			"full_name": "pPlanello/pPlanello",
			"private": false,
			"owner": {
					"login": "pPlanello",
					"id": 36472624,
					"node_id": "MDQ6VXNlcjM2NDcyNjI0",
					"avatar_url": "https://avatars.githubusercontent.com/u/36472624?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/pPlanello",
					"html_url": "https://github.com/pPlanello",
					"followers_url": "https://api.github.com/users/pPlanello/followers",
					"following_url": "https://api.github.com/users/pPlanello/following{/other_user}",
					"gists_url": "https://api.github.com/users/pPlanello/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/pPlanello/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/pPlanello/subscriptions",
					"organizations_url": "https://api.github.com/users/pPlanello/orgs",
					"repos_url": "https://api.github.com/users/pPlanello/repos",
					"events_url": "https://api.github.com/users/pPlanello/events{/privacy}",
					"received_events_url": "https://api.github.com/users/pPlanello/received_events",
					"type": "User",
					"site_admin": false
			},
			"html_url": "https://github.com/pPlanello/pPlanello",
			"description": null,
			"url": "https://api.github.com/repos/pPlanello/pPlanello",
			"created_at": new Date("2022-11-24T10:24:29Z"),
			"updated_at": new Date("2022-11-24T10:24:29Z"),
			"pushed_at": new Date("2023-06-06T11:41:10Z"),
			"git_url": "git://github.com/pPlanello/pPlanello.git",
			"ssh_url": "git@github.com:pPlanello/pPlanello.git",
			"clone_url": "https://github.com/pPlanello/pPlanello.git",
			"svn_url": "https://github.com/pPlanello/pPlanello",
			"homepage": null,
			"size": 145,
			"stargazers_count": 0,
			"watchers_count": 0,
			"language": null,
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"has_discussions": false,
			"forks_count": 0,
			"mirror_url": null,
			"archived": false,
			"disabled": false,
			"open_issues_count": 0,
			"license": null,
			"allow_forking": true,
			"is_template": false,
			"web_commit_signoff_required": false,
			"topics": [],
			"visibility": "public",
			"forks": 0,
			"open_issues": 0,
			"watchers": 0,
			"default_branch": "master",
			"permissions": {
					"admin": true,
					"maintain": true,
					"push": true,
					"triage": true,
					"pull": true
			}
	}
]